service: sentimentapi
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "comprehend:DetectSentiment"
            - "comprehend:DetectEntities"
            - "comprehend:DetectSyntax"
            - "comprehend:DetectKeyPhrases"
            - comprehend:DetectDominantLanguage
          Resource:
            - "*"
functions:
  sentimentAnalysis:
    handler: functions/sentimentAnalysis.sentimentAnalysis
    events:
      - http:
          path: /sentiment-analysis
          method: post
          cors: true
